---
- name: Ensure SSH public key is present on all servers
  hosts: all_servers
  gather_facts: false
  vars_files:
    - ../vaults/vault.yml
  vars:
    ansible_remote_tmp: /var/ansible_tmp
    ssh_public_key_path: "~/.ssh/id_rsa.pub"
    remote_user: "your_ssh_username" # <--- IMPORTANT: Replace with the actual remote username

  tasks:
    - name: Read SSH public key from local file
      slurp:
        src: "{{ ssh_public_key_path }}"
      register: ssh_key_content_slurp_result
      delegate_to: localhost

    - name: Add SSH public key to remote user's authorized_keys
      authorized_key:
        user: "{{ remote_user }}"
        state: present
        key: "{{ ssh_key_content_slurp_result['content'] | b64decode }}"
      become: true
      become_user: "{{ remote_user }}"